[package]
name = "done"
version = "0.1.3"
edition = "2021"
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
license = "MPL 2.0"
description = "Done is the ultimate task management solution for seamless organization and efficiency. "
homepage = "https://done.edfloreshz.dev/"
documentation = "https://docs.rs/done"
repository = "https://github.com/edfloreshz/done/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25", features = ["process"]}
strum_macros = "0.24.3"
i18n-embed-fl = "0.6.4"
once_cell = "1.13.0"
derive-new = "0.5.9"
reqwest = "0.11.13"
sysinfo = "0.27.5"
serde_json = "1.0"
anyhow = "1.0.56"
strum = "0.24.1"
tonic = "0.8.2"
glib = "0.16.2"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[dependencies.chrono]
version = "0.4.23"
features = ["serde"]

[dependencies.relm4]
version = "0.6.0-alpha.2"
features = ["macros", "libadwaita", "gnome_43"]

[dependencies.serde]
version = "1.0.126"
features = ["derive"]

[dependencies.gettext-rs]
version = "0.7"
features = ["gettext-system"]

[dependencies.rust-embed]
version = "6.4.0"
features = ["debug-embed"]

[dependencies.i18n-embed]
version = "0.13.4"
features = ["fluent-system", "desktop-requester"]

[dependencies.libset]
git = "https://github.com/edfloreshz/libset"
branch = "beta"

[dependencies.directories]
git = "https://github.com/edfloreshz/directories-rs"

[dependencies.done_provider]
git = "https://github.com/done-devel/proto-rust"

[build-dependencies]
glib-build-tools = "0.16.3"
